# Generated by Django 4.2.6 on 2023-11-19 02:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
    ]
